### ISSUE TITLE
Is this method online MOT?

### ISSUE THREAD

**Issue by zouhaoa** [hailanyi/3D-Multi-Object-Tracker#1]
Hi, thanks for your interesting work!
In your code, before saving results, the post_processing seems to filter out all trajectories with a score lower than the config.avg_score. In my understanding, this process makes your method unable to run online.
Looking forward to your reply.
Thanks.

**Comment by hailanyi** [comment]
Thanks for your attention. The code is designed for both online and global tracking use. The settings in the yaml files are global settings, it can achieve better tracking performance ( ~2 HOTA ) . You can set the ‘avg_score’ and ‘rec_misses’ to False to make it online. The other parameters, such as ‘init_score’ and ‘input_score’, also should be adjusted to obtain a desirable tracking performance.

**Comment by zouhaoa** [comment]
Can you show the performance of online MOT for fair comparison?
