### ISSUE TITLE
How to deal with the results output through the "OpenPCDet" framework？

### ISSUE THREAD

**Issue by stidk** [hailanyi/3D-Multi-Object-Tracker#10]
{'name': array(['Car', 'Car', 'Cyclist', 'Car', 'Car', 'Car', 'Cyclist',
'Pedestrian', 'Pedestrian', 'Cyclist'], dtype='<U10'), 'truncated': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), 'occluded': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), 'alpha': array([-4.515572 , -4.082801 , -8.211994 , -4.2358727, -6.37723 ,
-4.212622 , -7.653681 , -7.828194 , -3.5104022, -7.7533026],
dtype=float32), 'bbox': array([[ 390.46756, 182.59967, 420.16034, 202.18625],
[ 93.72412, 207.40984, 192.874 , 245.46086],
[ 676.26434, 162.27713, 691.895 , 190.43402],
[ 207.97661, 185.72922, 272.2654 , 217.085 ],
[ 771.51385, 172.55157, 896.3316 , 212.16136],
[ 217.41855, 188.42061, 271.71057, 213.47649],
[ 338.7873 , 181.46661, 348.29086, 203.7352 ],
[ 953.0622 , 152.42534, 984.1048 , 240.13443],
[1197.7362 , 145.42426, 1241. , 231.93535],
[ 214.69026, 177.82062, 222.83852, 203.2955 ]], dtype=float32), 'dimensions': array([[3.8072727 , 1.4813445 , 1.6003532 ],
[3.52273 , 1.3748183 , 1.8758411 ],
[1.6750405 , 1.752761 , 0.42281026],
[3.6912992 , 1.555141 , 1.5810864 ],
[4.483073 , 1.4696931 , 1.6517544 ],
[3.673051 , 1.4601415 , 1.5243837 ],
[1.5081377 , 1.6859876 , 0.39957428],
[0.8074811 , 1.77992 , 0.5690844 ],
[0.60090435, 1.7681558 , 0.5539663 ],
[1.5440738 , 1.6429834 , 0.31740588]], dtype=float32), 'location': array([[-16.576267 , 2.297428 , 58.48187 ],
[-20.094868 , 2.954785 , 31.181479 ],
[ 4.6577272, 1.0940528, 45.77933 ],
[-20.028645 , 2.286567 , 39.15602 ],
[ 8.54361 , 1.4581716, 28.02376 ],
[-23.375515 , 2.4971836, 46.22146 ],
[-20.705027 , 2.3634393, 56.004333 ],
[ 7.4708343, 1.3650522, 15.131747 ],
[ 12.740014 , 1.2072334, 15.104981 ],
[-25.844282 , 1.9757288, 47.61044 ]], dtype=float32), 'rotation_y': array([-4.790928 , -4.6516724, -8.111552 , -4.706223 , -6.0847206,
-4.678815 , -8.006577 , -7.3778024, -2.8195329, -8.248504 ],
dtype=float32), 'score': array([0.62366086, 0.5092147 , 0.45878437, 0.4128577 , 0.40351897,
0.3037016 , 0.15691371, 0.12470149, 0.10985158, 0.10319255],
dtype=float32), 'boxes_lidar': array([[ 58.771694 , 16.60492 , -0.842473 , 3.8072727 ,
1.6003532 , 1.4813445 , 3.2201314 ],
[ 31.478838 , 20.126875 , -1.8011765 , 3.52273 ,
1.8758411 , 1.3748183 , 3.0808759 ],
[ 46.06226 , -4.6421843 , 0.13941461, 1.6750405 ,
0.42281026, 1.752761 , 6.540756 ],
[ 39.445976 , 20.054586 , -0.960226 , 3.6912992 ,
1.5810864 , 1.555141 , 3.1354265 ],
[ 28.312376 , -8.526211 , -0.5928153 , 4.483073 ,
1.6517544 , 1.4696931 , 4.513924 ],
[ 46.512444 , 23.404373 , -1.1091216 , 3.673051 ,
1.5243837 , 1.4601415 , 3.1080184 ],
[ 56.294018 , 20.733837 , -0.788435 , 1.5081377 ,
0.39957428, 1.6859876 , 6.4357805 ],
[ 15.419843 , -7.4560823 , -0.46799874, 0.8074811 ,
0.5690844 , 1.77992 , 5.807006 ],
[ 15.392667 , -12.72664 , -0.37202018, 0.60090435,
0.5539663 , 1.7681558 , 1.2487365 ],
[ 47.89532 , 25.867668 , -0.45570797, 1.5440738 ,
0.31740588, 1.6429834 , 6.6777077 ]], dtype=float32), 'frame_id': '000001'}

The output is shown above,I hope to get your help,thank you.

**Comment by hailanyi** [comment]
KITTI detection dataset provided a development kit, which contains the description of bound ing box format. You need to save the OpenPCDet boxes to .txt file according to this format. Please refer to the detection results we provided.
