### ISSUE TITLE
a request

### ISSUE THREAD

**Issue by dodeokwangyooo** [hailanyi/3D-Multi-Object-Tracker#12]
I'm so happy that author write the A guide to submit results to KITTI test. This is the 3d method. Now I want to get the method of 2d results submit to the kitti . Can you help me?

**Comment by hailanyi** [comment]
You can use the same format and pad the 3d field with zeros. Something like: 

3D result
0 0 Car -1 -1 -10 0.0 206. 355. 374. 1.4491 1.6202 3.8693 -3.70 1.833 6.21 -4.7342 9.97671813719746

2D result
0 0 Car -1 -1 -10 0.0 206. 355. 374. 0 0 0 0 0 0 0 0
