### ISSUE TITLE
access to download detections (training & testing set)

### ISSUE THREAD

**Issue by fandulu** [hailanyi/3D-Multi-Object-Tracker#13]
Thanks for your great work. May I ask for your help to get access to download detections (training & testing set)?

**Comment by hailanyi** [comment]
I've changed the permissions and it's now available for download via the link in readme, or click [here](https://drive.google.com/file/d/1xDTXrKf3azvW0m6e3xMV1PluICRDstPk/view?usp=sharing)

**Comment by fandulu** [comment]
thanks very much

**Comment by fandulu** [comment]
Sorry, it seems that the link of kitti detection actually download the waymo detection.  Is it correct?

**Comment by hailanyi** [comment]
Ok, thank you for pointing out this problem, I updated again. The tracking performance on Waymo dataset is also released in readme, currently ranks third in waymo leadboard. If you can download both, please let me know.

**Comment by fandulu** [comment]
Got it. The KITTI is available now. Thanks again.
