### ISSUE TITLE
 How to visualize these result files？

### ISSUE THREAD

**Issue by hz-ants** [hailanyi/3D-Multi-Object-Tracker#14]
Thank for you great work.  evaluation/results/sha_key/data  **.txt , **.txt……How to visualize these result files？Same effect as this https://github.com/hailanyi/3D-Detection-Tracking-Viewer？Can you help me more specifically?Thank you

**Comment by hailanyi** [comment]
You can replace the ground truth of KITTI by the tracking results in ```evaluation/results/sha_key/data```. Then run the tracking viewer.
