### ISSUE TITLE
The pose file is obtained from the oxts files provided by KITTI tracking dataset using the official matlab tools.

### ISSUE THREAD

**Issue by Sonne-Zhu** [hailanyi/3D-Multi-Object-Tracker#17]
The pose file is obtained from the oxts files provided by KITTI tracking dataset using the official matlab tools.

_Originally posted by @hailanyi in https://github.com/hailanyi/3D-Multi-Object-Tracker/issues/11#issuecomment-1279639990_
  
Thank you for your great work！I have a question about pose.txt you provided: 

Using official matlab tools directly only seems to get the pose in IMU/GPS coordinate system, so did you convert it to lidar coordinate system? Because I found that your code seems to use only the external parameter between lidar and camera, i.e. velo_to_cam, but not use external parameter  between lidar and imu.

So is the pose.txt you provided in the lidar coordinate  system or in the IMU/GPS coordinate system?

**Comment by hoangduyloc** [comment]
> ```
>     The pose file is obtained from the oxts files provided by KITTI tracking dataset using the official matlab tools.
> ```
> 
> _Originally posted by @hailanyi in [#11 (comment)](https://github.com/hailanyi/3D-Multi-Object-Tracker/issues/11#issuecomment-1279639990)_
> 
> Thank you for your great work！I have a question about pose.txt you provided:
> 
> Using official matlab tools directly only seems to get the pose in IMU/GPS coordinate system, so did you convert it to lidar coordinate system? Because I found that your code seems to use only the external parameter between lidar and camera, i.e. velo_to_cam, but not use external parameter between lidar and imu.
> 
> So is the pose.txt you provided in the lidar coordinate system or in the IMU/GPS coordinate system?

Hi, I think this might help you: https://github.com/xinshuoweng/AB3DMOT/blob/master/AB3DMOT_libs/kitti_oxts.py

I also wonder the case, if we dont have the pose,  we have custom LIDAR only dataset, and after prediction we have 3D bboxes only. How can we apply this work?

**Comment by Sonne-Zhu** [comment]
> 



> > ```
> >     The pose file is obtained from the oxts files provided by KITTI tracking dataset using the official matlab tools.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > _Originally posted by @hailanyi in [#11 (comment)](https://github.com/hailanyi/3D-Multi-Object-Tracker/issues/11#issuecomment-1279639990)_
> > Thank you for your great work！I have a question about pose.txt you provided:
> > Using official matlab tools directly only seems to get the pose in IMU/GPS coordinate system, so did you convert it to lidar coordinate system? Because I found that your code seems to use only the external parameter between lidar and camera, i.e. velo_to_cam, but not use external parameter between lidar and imu.
> > So is the pose.txt you provided in the lidar coordinate system or in the IMU/GPS coordinate system?
> 
> Hi, I think this might help you: https://github.com/xinshuoweng/AB3DMOT/blob/master/AB3DMOT_libs/kitti_oxts.py
> 
> I also wonder the case, if we dont have the pose, we have custom LIDAR only dataset, and after prediction we have 3D bboxes only. How can we apply this work?

Thanks for the reply, so it looks like pose.txt is in imu/GPS coordinate, wouldn't it be necessary to convert it to lidar coordinate?
For your question, I think if there is no GPS to use as ground truth, performing an open source high precision lidar slam algorithm, such as LeGO-LOAM, to get lidar odometry is a viable method.

**Comment by hailanyi** [comment]
The pose is optional. If you don't have a pose, you can enter an 4x4 identity matrix instead.

**Comment by LvYanghao** [comment]
> The pose is optional. If you don't have a pose, you can enter an 4x4 identity matrix instead.

Just to add, it's the first three rows of a 4*4 matrix, because when the pose.txt is read, an additional row [0,0,0,1] will be appended at the end. Thanks again for your great work!
