### ISSUE TITLE
Predict 5 next trajectories

### ISSUE THREAD

**Issue by hoangduyloc** [hailanyi/3D-Multi-Object-Tracker#19]
Hi @hailanyi, thanks for your great work.

- I wanna try this work with these features:
1)  Estimate 5 next trajectories of objects to find the future path
2)  Calculate the velocity of each object
Can you address some keywords in your code, Thank you.

**Comment by hailanyi** [comment]
Sorry, currently  do not support this. But you can use different detections from different detectors, use different motion models, or use the multiple object proposals from the single object detector to obtain multiple trajectory predictions.
