### ISSUE TITLE
Cannot understand the idea of weight decay

### ISSUE THREAD

**Issue by Kemo-Huang** [hailanyi/3D-Multi-Object-Tracker#22]
The paper states that the previously missed objects should have larger search space so that they can be matched more easily.

I think it means that those objects should have smaller association costs. But in your code:

(1) The association weights (prediction scores) of previously missed objects are DECAYED LESS (1:15) than the ones of previously updated objects in the state prediction step. This means that previously missed objects will have larger association costs and they are harder to be matched.

(2) Detection confidences are ADDED to association weights (prediction scores) in the state update step. This means that objects with higher detection scores will have larger association costs. In addition, the weights of previously missed objects are ADDED LESS (1:10) than previously updated objects. This is the opposite weighting strategy in (1).

Your explanation of these two parts will be much appreciated.   : )

**Comment by hailanyi** [comment]
Just for paying more attention to recently updated objects. You can directly remove the 15 and 10, the results will not drop greatly. 
I also tested the 1-sigmoid(score) to update, but the results are not good. Maybe the prediction and detection are every accurate, so the search range is also should be smaller.
