### ISSUE TITLE
VirConv detections

### ISSUE THREAD

**Issue by Kemo-Huang** [hailanyi/3D-Multi-Object-Tracker#23]
Could you provide a download link for the VirConv model trained on KITTI 3D detection ''trainval'' set? The model zoo for VirConv only includes the model trained on ''train'' set.

I have read your paper and code of VirConv. It seems that the data preprocessing for VirConv detector is very complicated. Could you also provide a simple guide or demo code on how to generate input data and detection results on KITTI tracking dataset?

**Comment by hailanyi** [comment]
I recently focus on detection, I don't have much time to organize the tracking code. So currently have no plan to release the  preprocessing code for tracking.
