### ISSUE TITLE
Can we get a pre-trained model of PC3T?

### ISSUE THREAD

**Issue by FlyerMaxwell** [hailanyi/3D-Multi-Object-Tracker#4]
Hi,
I am doing a project about wireless sensing and want to use PC3T as a reference (ground truth). How could we get a pre-trained model for a first try on our own dataset?

**Comment by hailanyi** [comment]
You need to first train a detector using OpenPCDet on your own dataset to generate 3D detections results. Then, you can use this project and the detection results to generate the tracking results.
