### ISSUE TITLE
Gain no way to get testing label

### ISSUE THREAD

**Issue by Hale423** [hailanyi/3D-Multi-Object-Tracker#8]
Hi, I can't find any link to download the testing label, at least not on Kitti's official website, Can you please provide me the link  to testing label ? Thx a lot  =。=

**Comment by hailanyi** [comment]
I have updated a new tracker based on the CasA detections. We also released the [detections on the test set](https://drive.google.com/file/d/1LaousWNTldOV1IhdcGDRM_UGi5BFWDoN/view?usp=sharing).  More details are available in the readme.

**Comment by fandulu** [comment]
Excuse me, downloading the detection of the test set needs your permission, could you please approve our application?
